### PR TITLE
Merge XMR 12.2 

### PR DESCRIPTION
**Pull request by shopglobal**
This is a full rebase for ETNX up to v0.12.2.0 point release of the Monero software, and it is part of the v0.12 network wide update. The major release was due to a recent network update, which in turn decreased the network fees, sorted inputs so as not to leak wallet choice by inference, and slightly changed the proof-of-work algorithm to prevent DoS attacks by ASICs. This release of the software presents a number of major improvements to Monero, Electronero's code base as well as a large set of bug fixes some from Monero and some specific to Electronero.

Expect another update soon, as hard fork v12 was delayed pending further analysis of the Difficulty Algorithm. See comments below for data points and more information.

Some highlights of this point release are:

dns checkpoints updated
checkpoints updated
win32 support
hardening flags added to CMAKE machinery 
docker build updated Dockerfile fixed for new dependencies *(only linux, and could use some modifications for other operating systems) 
fix PCSC on windows (for Ledger support)
on_get_output_distribution was giving us issues in GUI so reverted to 12.0 methods(todo further analysis)
various build fixes regarding ICU, fPIC (need builders for all operating systems)
fix fee display unit when the unit is not the default
fixes for lengthy waits (and timeouts) when sending transactions and parsing ring history
automatically pop old version blocks if the user failed to update in time
fix sweep_unmixable output selection after the recent min ring size bump
sync fixes
document the need for building dependencies with -fPIC
fix bandwidth limit commands scaling
fix disabling logs (--log-level "")
reuse connections in the wallet API
fix reading some arguments from the config file
log stack trace on crash (wonky on windows)
fix loading the txpool with colliding key images
fix errors when the shared ringdb fails to initialize
fix destination ordering
fix endianness dependence in subaddress generation
fast scan mode for Ledger (exposes view key to the host computer)
Some highlights of this major release are:

tweaked PoW to block DoS attacks from ASICs
added input ordering to prevent wallet inference
subaddress support added, with addresses starting with a prefix of 8
added multisig support
added support for SunOS / Solaris
initial support for Ledger Nano S hardware wallet
added seed encryption by password
securely erase keys from memory, for most cases, when no longer in use
Bulletproofs implementation fully live on main net and test net
added accounts, tags, and labels, via subaddresses
added initial, quite rough support for 0MQ
added some mitigations for privacy-threatening key reusing forks
added a new network, stagenet, which mirrors mainnet's features
added SSL support for light wallet API
added CORS support to the RPC stack
added a --generate-from-spend-key flag to the CLI wallet
added a --disable-dns-checkpoints flag to the daemon
massive improvements to build hardening
added native fuzz testing for user input
added the ability to limit inbound connections
enabled "fluffy blocks" by default
added a --max-txpool-size mempool size limit flag
allow a remote node to temporarily process RPC requests during IBD
added a relay_tx command to the RPC wallet
allow for spend key retrieval via RPC wallet call
made libraries use position independent code
improvements made to Docker image
added a sweep_single command to the CLI wallet
made RPC error codes more specific
improved stack trace printing, and noted stack trace lib in output
split and refactored wallet_api from wallet code
added priority arguments to sweep_all and donate CLI wallet commands
added a --do-not-relay option to the CLI wallet
made the hashchain unit tests work again
added tests for subaddress expansion
added RingCT performance tests
added package installation instructions for Void Linux
made changes to ensure no sensitive data is logged accidentally
added a Croatian mnemonic word list
added a Lojban mnemonic word list
added a Swedish CLI translation
added an timeout for connections which don't complete a handshake
moved test building to the end of the CMake build process
as always, loads of bug fixes and performance improvements

### CODE REVIEW

**Comment by shopglobal** [comment]
Standing by for review @zhmrab @cryptobender69

**Comment by shopglobal** [comment]
This is the build we have been passing around to the pools with minor bugfixes.

**Comment by shopglobal** [comment]
When I [compiled this branch](https://github.com/electronero/electronero/releases/download/v12.2.4/electronero_ubuntu64-docker.tar.gz) on a node which had the "odd difficulties", I also ```./electronero-blockchain-import --pop``` enough blocks to put the node back to before the ETN>ETNX hard fork. Then import the [https://release.electronero.org/blockchain/blockchain.raw](blockchain.raw) and sync remaining blocks from the main chain. This seemed to stabilize the differences in the test nodes as seen below *(taken 48 hours ago)  Windows and Ubuntu 16.04 nodes difficulty match: nodes difficulty match

**Comment by shopglobal** [comment]
Earlier this week the difficulty rose abruptly as pools patched main nodes, that came along with a brief delay which was met with sharp decrease in network hashrate. 
Electronero LWMA Data Point Comparison:
Electronero LWMA Data Comparison 


Soon after the patches were applied difficulty rose sharply along with net hashrate.
Electronero LWMA Data Comparison 
Several hundred blocks (give or take ~5 hours later) later 
Electronero LWMA Data Comparison 
As expected, the LWMA performance has been reacting well to delays and hash attacks.Currently [Zawy's data collection regarding Electronero DAA](http://wordsgalore.com/diff/index4.html) (difficulty adjustment algorithm) has displayed decent results.  The server is maintained by Zawy, mathematician and blockchain theorist of whom we maintain contact with for advisory regarding the difficulty adjustment algorithm. See recent data at his site. 
200 blocks (~2.2 hours or so) later 
 Electronero LWMA Data Comparison 

The main reason for the difficulty adjustment in the first place is SMA which is employed by Monero protocol would react harsh to new blockchain, serving fast blocks to hash attackers and leaving the network "stalled" for hours (as we have seen with ETN network time and time again) once the attacks cease. These other networks using SMA with weak hash support comparative to the overall Network hashrate is causing their transactions to fail and puts their users coins at risk. This is why we work hard to keep the blocks moving on schedule

**Review by protradingclub — APPROVED** [review]

**Pull request merged**
