### PR TITLE
Fix a Timing issue raised by a simple misspelling missed in compile time

### PR DESCRIPTION
**Pull request by shopglobal**
Compile time didn't catch it, not sure how.

### CODE REVIEW

**Comment by shopglobal** [comment]
Human eye helps! Thanks to git history and a fork, this was caught. Probably would help out the abnormality in the diff which is observed all that much more often on some pools who run in certain timezone for whatever reason

**Comment by sumoclassic** [comment]
Can’t believe compile didn’t catch it. 

Approved

**Review by sumoclassic — APPROVED** [review]

**Comment by shopglobal** [comment]
Let's get this merged @mannie65 where are you on the review?

**Review by billaure — APPROVED** [review]
yes this makes sense is that what you're asking or is this required?

**Comment by shopglobal** [comment]
2 reviews and simple stuff like this get's merged fast

**Pull request merged**
