### PR TITLE
error resolution ...

### PR DESCRIPTION
**Pull request by swa74**
2018-07-09 19:10:39.481 [P2P4]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:310 [24.113.201.21:51442 INC] Sync data returned a new top block candidate: 326584 -> 339612 [Your node is 13028 blocks (9 days) behind]
SYNCHRONIZATION started
2018-07-09 19:10:40.213 [P2P0]  ERROR   blockchain      src/cryptonote_core/blockchain.cpp:3517 !!!!!!!!! difficulty overhead !!!!!!!!!

### CODE REVIEW

**Comment by shopglobal** [comment]
Best outcome is met by importing the blockchain.raw as we examine the solutions. Checkpoints may work, we're trying it out. Does it work on your branch?

Here's the link to blockchain.raw
https://release.electronero.org/blockchain/blockchain.raw

```electronero-blockchain-import --batch-size 20000 --database lmdb#fastest --guard-against-pwnage 0```

**Comment by swa74** [comment]
I did just that, downloaded the link, completely imported it, but after running the daemon I get an error

**Comment by swa74** [comment]
I already have several working pools, for example, http://italocoin.ru, I want to join your community

**Comment by swa74** [comment]
I'm already 2 days trying to synchronize the demon, but not successfully. I tried and direct synchronization and import of the file, I get the same error

**Comment by shopglobal** [comment]
Run the import tool, twice ```electronero-blockchain-import --batch-size 20000 --database lmdb#fastest --guard-against-pwnage 0```

**Comment by swa74** [comment]
Well, I'll try and write off tomorrow what came of it

**Review by shopglobal — APPROVED** [review]

**Comment by swa74** [comment]
electronero/electronero-blockchain-import --batch-size 20000 --database lmdb#fastest --guard-against-pwnage 0 --input-file ~/blockchain.raw --data-dir ~/.electronero/

**Comment by shopglobal** [comment]
Yes, once will catch up to certain block. Twice will pass the Hard Fork

**Comment by shopglobal** [comment]
Pool ops are using these bins on Ubuntu64

https://github.com/electronero/electronero/releases/download/12.2.9/electronero-12.2.9_ubuntu64.zip

Install Dependencies for Ubuntu
```sudo apt install build-essential cmake libboost-all-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libcurl4-openssl-dev libgtest-dev libreadline-dev libminiupnpc-dev libzmq3-dev```

**Comment by swa74** [comment]
Thanks, everything turned out after the 2nd pass, I will test the pool, then I'll apply for adding the pool to the general list

**Comment by shopglobal** [comment]
I knew it would, we are looking forward to having you on board. If you would join us on telegram so we can communicate easier? https://t.me/electronero
I will share the config and add you to the pool operators private chat group. 


My personal telegram is https://t.me/interchained

**Comment by swa74** [comment]
Thank you, but it's too late for us today and I'll go to bed, tomorrow I'll check the pool and be sure to contact you

**Comment by shopglobal** [comment]
Have a nice night!

**Pull request merged**
